services:
  server:
    build: .
    container_name: ciiccte-server
    command: uv run fastapi dev src/main.py --host 0.0.0.0   
    ports:
      - "8000:8000"
    networks:
      - db
networks:
  db:
    name: db-net
    external: true
